# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-04 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_id', models.CharField(max_length=30, verbose_name='\u5e8f\u53f7')),
                ('enname', models.CharField(max_length=30, verbose_name='\u82f1\u6587\u540d')),
                ('cnname', models.CharField(max_length=30, verbose_name='\u4e2d\u6587\u540d')),
            ],
            options={
                'verbose_name': 'system',
                'verbose_name_plural': 'system',
            },
        ),
    ]
